export const productArr = [
  {
    id: 1,
    title: 'Buckle Wrap Wooden Table',
    brand: 'Brand Name',
    description: '',
    price: 52,
    quantity: 1,
    sale: {
      salePrice: 40,
    },
    img: 'https://dummyimage.com/275x360/ebebeb/000',
    thumbnail: 'https://dummyimage.com/150x150/ebebeb/000',
    newProduct: false,
    productImages: [
      {
        id: 1,
        img: 'https://dummyimage.com/800x400/000/fff',
        imgMobile: 'https://dummyimage.com/400x600/000/fff',
      },
      {
        id: 2,
        img: 'https://dummyimage.com/800x400/000/fff',
        imgMobile: 'https://dummyimage.com/400x600/000/fff',
      },
      {
        id: 3,
        img: 'https://dummyimage.com/800x400/000/fff',
        imgMobile: 'https://dummyimage.com/400x600/000/fff',
      },
    ],
  },
  {
    id: 2,
    title: 'Wooden Coffee Mug',
    brand: 'Brand Name',
    description: '',
    price: 23.99,
    quantity: 1,
    sale: false,
    img: 'https://dummyimage.com/275x360/ebebeb/000',
    thumbnail: 'https://dummyimage.com/150x150/ebebeb/000',
    newProduct: false,
  },
  {
    id: 3,
    title: 'Wooden Bluetooth Speaker',
    brand: 'Brand Name',
    description: '',
    price: 23,
    quantity: 1,
    sale: false,
    img: 'https://dummyimage.com/275x360/ebebeb/000',
    thumbnail: 'https://dummyimage.com/150x150/ebebeb/000',
    newProduct: true,
  },
  {
    id: 4,
    title: 'Wood White Chair',
    brand: 'Brand Name',
    description: '',
    price: 17,
    quantity: 1,
    sale: false,
    img: 'https://dummyimage.com/275x360/ebebeb/000',
    thumbnail: 'https://dummyimage.com/150x150/ebebeb/000',
    newProduct: false,
  },
  {
    id: 5,
    title: 'Buckle Wrap Wooden Table',
    brand: 'Brand Name',
    description: '',
    price: 99,
    quantity: 1,
    sale: {
      salePrice: 49.99,
    },
    img: 'https://dummyimage.com/275x360/ebebeb/000',
    thumbnail: 'https://dummyimage.com/150x150/ebebeb/000',
    newProduct: false,
  },
  {
    id: 6,
    title: 'Wooden Coffee Mug',
    brand: 'Brand Name',
    description: '',
    price: 23.99,
    quantity: 1,
    sale: false,
    img: 'https://dummyimage.com/275x360/ebebeb/000',
    thumbnail: 'https://dummyimage.com/150x150/ebebeb/000',
    newProduct: false,
  },
  {
    id: 7,
    title: 'Wooden Bluetooth Speaker',
    brand: 'Brand Name',
    description: '',
    price: 72,
    quantity: 1,
    sale: false,
    img: 'https://dummyimage.com/275x360/ebebeb/000',
    thumbnail: 'https://dummyimage.com/150x150/ebebeb/000',
    newProduct: true,
  },
  {
    id: 8,
    title: 'Wood White Chair',
    brand: 'Brand Name',
    description: '',
    price: 45,
    quantity: 1,
    sale: false,
    img: 'https://dummyimage.com/275x360/ebebeb/000',
    thumbnail: 'https://dummyimage.com/150x150/ebebeb/000',
    newProduct: false,
  },
  // {
  //   id: 9,
  //   title: 'Wood White Chair',
  //   brand: 'Brand Name',
  //   description: '',
  //   price: 25,
  //   quantity: 1,
  //   sale: false,
  //   img: 'https://dummyimage.com/275x360/ebebeb/000',
  //   thumbnail: 'https://dummyimage.com/150x150/ebebeb/000',
  //   newProduct: false,
  // },
]

export const productObj = {
  id: 1,
  title: 'Buckle Wrap Wooden Table',
  brand: 'Brand Name',
  description: '',
  price: 52,
  quantity: 1,
  sale: {
    salePrice: 40,
  },
  newProduct: false,
}
export const productObjTwo = {
  id: 2,
  title: 'Wooden Coffee Mug',
  brand: 'Brand Name',
  description: '',
  price: 23.99,
  quantity: 1,
  sale: false,
  newProduct: false,
}
export const productObjThree = {
  id: 3,
  title: 'Wooden Bluetooth Speaker',
  brand: 'Brand Name',
  description: '',
  price: 23,
  quantity: 1,
  sale: false,
  newProduct: true,
}
export const productObjFour = {
  id: 4,
  title: 'Wood White Chair',
  brand: 'Brand Name',
  description: '',
  price: 45,
  quantity: 1,
  sale: false,
  newProduct: false,
}
